name: Run macOS in Cloud
on: 
  workflow_dispatch:

jobs:
  run-macos:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run macOS Container
      run: |
        docker run -d --name macos -p 8006:8006 --device=/dev/kvm --cap-add=NET_ADMIN -e DISK_SIZE=50G dockur/macos
        sudo apt-get update && sudo apt-get install tmate -y
        tmate -S /tmp/tmate.sock new-session -d
        tmate -S /tmp/tmate.sock wait tmate-ready
        echo "=== DANE LOGOWANIA DO TWOJEJ MASZYNY ==="
        tmate -S /tmp/tmate.sock display -p '#{tmate_web}'
        echo "========================================"
        sleep 21600
